# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editpass.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json



class Ui_editpassWin(object):
    def setupUi(self, editpassWin):
        editpassWin.setObjectName("editpassWin")
        editpassWin.resize(770, 530)
        self.titleLabel = QtWidgets.QLabel(editpassWin)
        self.titleLabel.setGeometry(QtCore.QRect(200, 10, 371, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.nameLabel = QtWidgets.QLabel(editpassWin)
        self.nameLabel.setGeometry(QtCore.QRect(90, 90, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.nameDropDown = QtWidgets.QComboBox(editpassWin)
        self.nameDropDown.setGeometry(QtCore.QRect(300, 100, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        self.nameDropDown.setFont(font)
        self.nameDropDown.setObjectName("nameDropDown")
        self.nameDropDown.clearFocus()
        self.usernameLabel = QtWidgets.QLabel(editpassWin)
        self.usernameLabel.setGeometry(QtCore.QRect(90, 250, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setObjectName("usernameLabel")
        self.urlLabel = QtWidgets.QLabel(editpassWin)
        self.urlLabel.setGeometry(QtCore.QRect(90, 160, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        self.urlLabel.setFont(font)
        self.urlLabel.setObjectName("urlLabel")
        self.passwordLabel = QtWidgets.QLabel(editpassWin)
        self.passwordLabel.setGeometry(QtCore.QRect(90, 340, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setObjectName("passwordLabel")
        self.passwordLine = QtWidgets.QLineEdit(editpassWin)
        self.passwordLine.setGeometry(QtCore.QRect(270, 340, 391, 41))
        self.passwordLine.setObjectName("passwordLine")
        self.usernameLine = QtWidgets.QLineEdit(editpassWin)
        self.usernameLine.setGeometry(QtCore.QRect(270, 260, 391, 41))
        self.usernameLine.setObjectName("usernameLine")
        self.urlLine = QtWidgets.QLineEdit(editpassWin)
        self.urlLine.setGeometry(QtCore.QRect(270, 180, 431, 41))
        self.urlLine.setObjectName("urlLine")
        self.usernameCopy = QtWidgets.QPushButton(editpassWin)
        self.usernameCopy.setGeometry(QtCore.QRect(670, 260, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.usernameCopy.setFont(font)
        self.usernameCopy.setObjectName("usernameCopy")
        self.passwordCopy = QtWidgets.QPushButton(editpassWin)
        self.passwordCopy.setGeometry(QtCore.QRect(670, 340, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.passwordCopy.setFont(font)
        self.passwordCopy.setObjectName("passwordCopy")
        self.saveButton = QtWidgets.QPushButton(editpassWin)
        self.saveButton.setGeometry(QtCore.QRect(110, 420, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        self.deleteButton = QtWidgets.QPushButton(editpassWin)
        self.deleteButton.setGeometry(QtCore.QRect(440, 420, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        self.deleteButton.setFont(font)
        self.deleteButton.setObjectName("deleteButton")

        self.retranslateUi(editpassWin)
        QtCore.QMetaObject.connectSlotsByName(editpassWin)
        self.parse(editpassWin)

    def retranslateUi(self, editpassWin):
        _translate = QtCore.QCoreApplication.translate
        editpassWin.setWindowTitle(_translate("editpassWin", "Edit passwords"))
        self.titleLabel.setText(_translate("editpassWin", "Edit or View passwords"))
        self.nameLabel.setText(_translate("editpassWin", "Select name"))
        self.usernameLabel.setText(_translate("editpassWin", "Username/ \n"
" Email"))
        self.urlLabel.setText(_translate("editpassWin", "Website/ \n"
" application"))
        self.passwordLabel.setText(_translate("editpassWin", "Password"))
        self.usernameCopy.setText(_translate("editpassWin", "Copy"))
        self.passwordCopy.setText(_translate("editpassWin", "Copy"))
        self.saveButton.setText(_translate("editpassWin", "Save Changes"))
        self.deleteButton.setText(_translate("editpassWin", "Delete Password"))
    
    def parse(self, editpassWin):
        names = []
        for obj in reader()["objects"]:
            names.append(obj["name"])
        print(names)
        for name in names:
            self.nameDropDown.addItem(name)
        


#functions to speed up json read write process in other parts of program
def reader():
    with open("pass.json") as f:
        return json.load(f)

def writer(d):
    with open("pass.json", "w") as f:
        json.dump(d,f)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editpassWin = QtWidgets.QWidget()
    ui = Ui_editpassWin()
    ui.setupUi(editpassWin)
    editpassWin.show()
    sys.exit(app.exec_())
